// The Battle Catalog's shape (R32.1).
//
// PokeSwap's own read-only description of Generation VI (ORAS), generated by
// `scripts/battle-catalog/build.mjs` from pinned sources. Client and server
// read the same files; nothing here is mutable and nothing is fetched at play
// time.
//
// What this is *not*: it is not a battle engine and not a Pokémon you own. The
// rules that execute a move are R32.3, and the individual with its nature, IVs
// and EVs is `PokemonInstance` (R32.2). This layer only answers "what is this
// species / move / ability, under Gen VI".

export type TypeName =
  | 'normal' | 'fighting' | 'flying' | 'poison' | 'ground' | 'rock' | 'bug' | 'ghost' | 'steel'
  | 'fire' | 'water' | 'grass' | 'electric' | 'psychic' | 'ice' | 'dragon' | 'dark' | 'fairy'

export type MoveCategory = 'physical' | 'special' | 'status'

/** How a move is meant to resolve, in PokeSwap's own words (see `effects.mjs`). */
export type MoveEffectId =
  | 'damage' | 'damage.multiHit' | 'damage.drain' | 'damage.recoil' | 'damage.selfKo'
  | 'damage.recharge' | 'damage.ailment' | 'damage.statChange' | 'damage.flinch'
  | 'ailment' | 'statChange' | 'heal' | 'protect' | 'ohko' | 'forceSwitch'
  | 'fieldEffect.side' | 'fieldEffect.all' | 'unique'

/** The statuses and volatiles the source tables name; our rules run a subset. */
export type AilmentName = string

/** Base stats, always in this order: HP, Attack, Defense, Sp. Atk, Sp. Def, Speed. */
export type BaseStats = readonly [number, number, number, number, number, number]

export interface CatalogSpecies {
  readonly id: number
  /** Canonical identifier, e.g. `nidoran-f`. Display names stay in the product. */
  readonly name: string
  /** 3–255; the capture formula reads this. */
  readonly catchRate: number
  readonly growthRate: string | null
  /** -1 genderless, else eighths of a chance of being female. */
  readonly genderRate: number
  readonly baseHappiness: number
}

/**
 * One battle-relevant form of a species. Every species has exactly one default
 * form; Deoxys, Rotom, Giratina, Wormadam and the Gen VI megas have more, and
 * they carry their own types, stats and abilities.
 */
export interface CatalogForm {
  readonly id: number
  readonly speciesId: number
  readonly name: string
  /** `null` for the default form, else e.g. `attack`, `mega-x`. */
  readonly formName: string | null
  readonly isDefault: boolean
  readonly isMega: boolean
  readonly isBattleOnly: boolean
  readonly types: readonly TypeName[]
  readonly baseStats: BaseStats
  readonly abilities: {
    readonly slot1: number | null
    readonly slot2: number | null
    readonly hidden: number | null
  }
}

export interface CatalogAbility {
  readonly id: number
  readonly name: string
}

export interface CatalogNature {
  readonly id: number
  readonly name: string
  /** Stat identifier raised by 10 %, or null for the neutral natures. */
  readonly increased: string | null
  readonly decreased: string | null
}

/** Only the departures from 1× are stored; everything absent is neutral. */
export type TypeChart = Readonly<Record<TypeName, Readonly<Partial<Record<TypeName, number>>>>>

export interface CatalogMoveMeta {
  readonly ailment: AilmentName | null
  readonly ailmentChance: number | null
  readonly statChance: number | null
  readonly flinchChance: number | null
  readonly critRate: number | null
  /** Percentage of the damage dealt that heals the user; negative is recoil. */
  readonly drain: number | null
  /** Percentage of max HP healed. */
  readonly healing: number | null
  readonly minHits: number | null
  readonly maxHits: number | null
}

export interface CatalogMove {
  readonly id: number
  readonly name: string
  readonly type: TypeName
  readonly category: MoveCategory
  /** `null` for status moves. */
  readonly power: number | null
  /** `null` means it cannot miss. */
  readonly accuracy: number | null
  readonly pp: number
  readonly priority: number
  readonly target: string
  readonly flags: readonly string[]
  readonly effectId: MoveEffectId
  /** True when R32.3's rules are expected to be able to run it as described. */
  readonly supported: boolean
  /** Present when `supported` is false: what is missing, in one phrase. */
  readonly unsupportedReason?: string
  readonly meta: CatalogMoveMeta
  /** The row this came from, so any value can be traced back to its source. */
  readonly source: { readonly effectId: number; readonly category: string }
}

/** ORAS learnset of one form. Level entries are `[moveId, level]`. */
export interface CatalogLearnset {
  readonly level: readonly (readonly [number, number])[]
  readonly machine: readonly number[]
  readonly egg: readonly number[]
  readonly tutor: readonly number[]
}

export interface CatalogProvenance {
  readonly ruleset: string
  readonly scope: string
  readonly sources: readonly {
    readonly id: string
    readonly role: string
    readonly repo?: string
    readonly commit?: string
    readonly license?: string
  }[]
  readonly trademarks: string
  readonly generatedFrom: Readonly<Record<string, { readonly bytes: number; readonly sha256: string }>>
}

export interface BattleCatalog {
  readonly catalogVersion: string
  readonly provenance: CatalogProvenance
  readonly types: readonly { readonly id: number; readonly name: TypeName }[]
  readonly typeChart: TypeChart
  readonly natures: readonly CatalogNature[]
  readonly abilities: readonly CatalogAbility[]
  readonly species: readonly CatalogSpecies[]
  readonly forms: readonly CatalogForm[]
  readonly moves: readonly CatalogMove[]
}
