// The Boss Room (D1.2.2 §9–§16).
//
// The last floor stops being "the procedural floor with an Alpha standing on
// the stairs". It is a designed space: an antechamber you walk into, a door,
// and one wide oval hall with a clear middle, decorated at the edges, big
// enough for four trainers, four Pokémon, an Alpha at twice the size and the
// effects a Boss Skill throws around.
//
// Everything here is pure: tiles in, tiles out, deterministic from the seed, so
// the layout can be tested without a canvas and regenerated by a server.

import { streamFor } from './rng'
import type { FloorPlan } from './floorPlan'
import {
  CELL_TILES, PATH_WIDTH, WALKABLE, type FloorTiles, type TileKind, type TilePoint,
} from './tileKinds'
import type { DungeonTheme } from './tiers'

/**
 * PLAYTEST PARAMETERS. The hall is an oval; these are its radii in tiles.
 * A party of four plus their Pokémon is eight bodies, the Alpha is two tiles
 * across, and a Boss Skill wants room around all of it — so the clear middle is
 * deliberately larger than anything the rules currently need.
 */
export const BOSS_ROOM = {
  hallRadiusX: 17,
  hallRadiusY: 12,
  /** No decor inside this radius: the fight happens here. */
  clearRadius: 10,
  antechamberRadiusX: 9,
  antechamberRadiusY: 7,
  /** Tiles between the two, which is where the door stands. */
  corridor: 7,
  corridorWidth: PATH_WIDTH.main,
} as const

export interface BossSlots {
  /** Where the Alpha waits. Never the door, never a spawn. */
  readonly alpha: TilePoint
  /** One per player, just inside the door. */
  readonly trainers: readonly TilePoint[]
  /** One per player's Pokémon, between their trainer and the Alpha. */
  readonly allies: readonly TilePoint[]
  /** The doorway tile, and the tile in front of it on the antechamber side. */
  readonly door: TilePoint
  readonly approach: TilePoint
  /** Middle of the hall: what the camera and the effects treat as the arena. */
  readonly centre: TilePoint
}

export interface BossFloor extends FloorTiles {
  readonly boss: BossSlots
}

export const isBossFloor = (tiles: FloorTiles): tiles is BossFloor =>
  'boss' in tiles && (tiles as BossFloor).boss !== undefined

const MAX_PLAYERS = 4

/** Fills an ellipse with `kind`, rounded the way the rest of the cave is. */
function oval(
  tiles: TileKind[], width: number, cx: number, cy: number, rx: number, ry: number,
  paint: (x: number, y: number) => TileKind,
): void {
  for (let y = Math.floor(cy - ry); y <= Math.ceil(cy + ry); y++) {
    for (let x = Math.floor(cx - rx); x <= Math.ceil(cx + rx); x++) {
      const dx = (x - cx) / rx
      const dy = (y - cy) / ry
      if (dx * dx + dy * dy > 1) continue
      tiles[y * width + x] = paint(x, y)
    }
  }
}

/**
 * Builds the last floor: antechamber, corridor, door, hall.
 *
 * The biome is the dungeon's own (§11): the same materials and the same props
 * the rest of this dungeon has been using, so the hall reads as the final room
 * of *this* cave and not as a generic arena.
 */
export function buildBossRoom(plan: FloorPlan, theme: DungeonTheme, seed: number): BossFloor {
  const rng = streamFor(seed, 'bossRoom', theme, plan.floor)
  const { hallRadiusX, hallRadiusY, antechamberRadiusX, antechamberRadiusY, corridor, corridorWidth } = BOSS_ROOM

  // The map is exactly what the room needs plus a rim of rock.
  const margin = 6
  const width = Math.max(CELL_TILES.w, hallRadiusX * 2 + margin * 2)
  const height = hallRadiusY * 2 + corridor + antechamberRadiusY * 2 + margin * 2
  const tiles: TileKind[] = new Array<TileKind>(width * height).fill('rock')

  const cx = Math.floor(width / 2)
  const hallCy = margin + hallRadiusY
  const doorY = hallCy + hallRadiusY
  const anteCy = doorY + corridor + antechamberRadiusY

  // Hall floor, with a ring of biome patches around the clear middle.
  oval(tiles, width, cx, hallCy, hallRadiusX, hallRadiusY, (x, y) => {
    const dx = (x - cx) / hallRadiusX
    const dy = (y - hallCy) / hallRadiusY
    const edge = Math.sqrt(dx * dx + dy * dy)
    if (edge > 0.72 && rng.chance(0.35)) return 'accent'
    if (edge > 0.55 && rng.chance(0.25)) return 'rubble'
    return 'floor'
  })

  // Antechamber.
  oval(tiles, width, cx, anteCy, antechamberRadiusX, antechamberRadiusY, () => (rng.chance(0.12) ? 'rubble' : 'floor'))

  // The passage between them, wide enough for the whole party to walk together.
  const half = Math.floor(corridorWidth / 2)
  for (let y = doorY - 1; y <= anteCy; y++) {
    for (let dx = -half; dx <= half; dx++) tiles[y * width + cx + dx] = 'floor'
  }

  const slots = layoutSlots({ x: cx, y: hallCy }, { x: cx, y: doorY })
  const draft: FloorTiles = {
    width,
    height,
    tiles,
    entrance: { x: cx, y: anteCy + 2 },
    // `exit` is what the rules call "the way on": here it is the doorway, which
    // is where the antechamber prompt appears.
    exit: slots.approach,
    roomCentres: { 0: { x: cx, y: anteCy }, 1: { x: cx, y: hallCy } },
    theme,
  }
  return { ...draft, boss: slots }
}

/**
 * Explicit spots (§14). The Alpha holds the north of the hall, the trainers
 * come in at the south, and each ally stands between their trainer and the
 * Alpha — so the room reads front to back the moment it opens.
 */
export function layoutSlots(centre: TilePoint, door: TilePoint): BossSlots {
  // D1.2.4bis §2: close quarters. Our Pokémon stand two tiles off the Alpha and
  // the trainer three behind them, so the three ranks read as one confrontation
  // instead of a hall with people at both ends. The middle slots are filled
  // first, which is what a solo run sees.
  const alpha = { x: centre.x, y: centre.y - 4 }
  const allyRow = alpha.y + 2
  const trainerRow = allyRow + 3
  const spread = [-1, 1, -3, 3]
  return {
    alpha,
    trainers: spread.slice(0, MAX_PLAYERS).map(dx => ({ x: centre.x + dx, y: trainerRow })),
    allies: spread.slice(0, MAX_PLAYERS).map(dx => ({ x: centre.x + dx, y: allyRow })),
    door,
    approach: { x: door.x, y: door.y + 2 },
    centre,
  }
}

/** True when a prop may stand here: inside the hall but outside the arena. */
export function isBossDecorSpot(boss: BossSlots, x: number, y: number): boolean {
  const dx = x - boss.centre.x
  const dy = (y - boss.centre.y) * (BOSS_ROOM.hallRadiusX / BOSS_ROOM.hallRadiusY)
  return Math.hypot(dx, dy) > BOSS_ROOM.clearRadius
}

/** Every slot the fight needs, for the tests and for the staging. */
export const bossOccupancy = (boss: BossSlots): TilePoint[] =>
  [boss.alpha, ...boss.trainers, ...boss.allies, boss.door, boss.approach]

export const isWalkableKind = (kind: TileKind): boolean => WALKABLE.has(kind)
