// From a floor plan to a walkable cave (D1 §6).
//
// The reference is Mt. Coronet and the classic Pokémon caves: rooms joined by
// corridors, rock everywhere, water you cross on a bridge, narrow passes and
// small side branches — not a grid of identical boxes. The biome layer paints
// the same cave as snow, forest, water, volcanic, ruins or crystal, so a
// dungeon still looks like the same game as WildLands rather than a minigame.
//
// Deterministic from the floor's own seed, so the map a player sees can be
// regenerated by a server that has the seed.

import { streamFor } from './rng'
import type { FloorPlan, FloorRoom } from './floorPlan'
import type { DungeonTheme } from './tiers'

export type TileKind =
  | 'rock'      // solid wall
  | 'floor'     // walkable cave floor
  | 'rubble'    // walkable, visually broken up
  | 'water'     // blocked unless bridged
  | 'bridge'    // walkable over water
  | 'ledge'     // a drop: walkable, marks a level change
  | 'accent'    // biome decoration: crystal, snowdrift, moss, lava crust
  | 'stairs'    // the way down, where the exit door is

export const WALKABLE: ReadonlySet<TileKind> = new Set<TileKind>(['floor', 'rubble', 'bridge', 'ledge', 'stairs', 'accent'])

/** How many tiles one plan cell is worth. Big enough to feel like a room. */
export const CELL_TILES = { w: 9, h: 7 } as const

export interface TilePoint { readonly x: number; readonly y: number }

export interface FloorTiles {
  readonly width: number
  readonly height: number
  /** Row-major, `width * height` long. */
  readonly tiles: TileKind[]
  readonly entrance: TilePoint
  readonly exit: TilePoint
  /** Tile centre of each room, for placing things. */
  readonly roomCentres: Readonly<Record<number, TilePoint>>
  readonly theme: DungeonTheme
}

/** The decoration each biome paints over the same cave. */
export const THEME_LOOK: Readonly<Record<DungeonTheme, { accent: string; water: string; name: string }>> = {
  cave: { accent: '#6b7a99', water: '#2a4a6b', name: 'cueva' },
  mine: { accent: '#8a7a5a', water: '#33405c', name: 'cueva + mina' },
  glacier: { accent: '#bfe3ff', water: '#3a6d93', name: 'cueva + nieve' },
  forest: { accent: '#4c7a4a', water: '#2f5d55', name: 'cueva + bosque' },
  volcano: { accent: '#a5462c', water: '#7a2f18', name: 'cueva + volcánico' },
  ruin: { accent: '#9c8f72', water: '#35506b', name: 'cueva + ruinas' },
  tower: { accent: '#7b6fa8', water: '#3b3d72', name: 'cueva + cristales' },
}

const index = (tiles: FloorTiles, x: number, y: number): number => y * tiles.width + x

export const tileAt = (tiles: FloorTiles, x: number, y: number): TileKind =>
  x < 0 || y < 0 || x >= tiles.width || y >= tiles.height ? 'rock' : tiles.tiles[index(tiles, x, y)]

export const isWalkable = (tiles: FloorTiles, x: number, y: number): boolean =>
  WALKABLE.has(tileAt(tiles, x, y))

const roomRect = (room: FloorRoom) => {
  const left = room.gx * CELL_TILES.w + 2
  const top = room.gy * CELL_TILES.h + 1
  return { left, top, w: Math.max(3, room.w * 2), h: Math.max(3, room.h * 2) }
}

/** Rooms are carved as rooms, not as rectangles of identical size. */
function carveRoom(tiles: TileKind[], width: number, room: FloorRoom, paint: (x: number, y: number) => TileKind): void {
  const rect = roomRect(room)
  for (let y = rect.top; y < rect.top + rect.h; y++) {
    for (let x = rect.left; x < rect.left + rect.w; x++) {
      // Rounded corners so the room reads as a cave chamber, not a box.
      const corner = (x === rect.left || x === rect.left + rect.w - 1)
        && (y === rect.top || y === rect.top + rect.h - 1)
      if (corner) continue
      tiles[y * width + x] = paint(x, y)
    }
  }
}

function carveCorridor(tiles: TileKind[], width: number, from: TilePoint, to: TilePoint, wide: boolean): void {
  const put = (x: number, y: number) => {
    if (tiles[y * width + x] === 'rock') tiles[y * width + x] = 'floor'
  }
  let { x, y } = from
  while (x !== to.x) {
    put(x, y)
    if (wide) put(x, y + 1)
    x += x < to.x ? 1 : -1
  }
  while (y !== to.y) {
    put(x, y)
    if (wide) put(x + 1, y)
    y += y < to.y ? 1 : -1
  }
  put(to.x, to.y)
}

export function buildFloorTiles(plan: FloorPlan, theme: DungeonTheme, seed: number): FloorTiles {
  const rng = streamFor(seed, 'tiles', theme, plan.floor)
  const width = (plan.width + 1) * CELL_TILES.w
  const height = (plan.height + 1) * CELL_TILES.h
  const tiles: TileKind[] = new Array(width * height).fill('rock')

  const centres: Record<number, TilePoint> = {}
  for (const room of plan.rooms) {
    const rect = roomRect(room)
    centres[room.id] = { x: rect.left + Math.floor(rect.w / 2), y: rect.top + Math.floor(rect.h / 2) }
    carveRoom(tiles, width, room, () => {
      const roll = rng.next()
      if (roll < 0.06) return 'accent'
      if (roll < 0.12) return 'rubble'
      return 'floor'
    })
  }

  // Corridors: some narrow, some wide, so the floor has passes and not just halls.
  for (const link of plan.links) {
    const from = centres[link.from]
    const to = centres[link.to]
    if (from && to) carveCorridor(tiles, width, from, to, rng.chance(0.35))
  }

  // A water body with a bridge: the classic cave crossing. Deep floors get it
  // more often, and the bridge always sits on the corridor so nothing is cut off.
  if (rng.chance(0.4 + plan.difficulty.depth * 0.3) && plan.rooms.length > 3) {
    const room = plan.rooms[rng.int(1, plan.rooms.length - 1)]
    const rect = roomRect(room)
    const bridgeY = centres[room.id].y
    for (let y = rect.top + 1; y < rect.top + rect.h - 1; y++) {
      for (let x = rect.left + 1; x < rect.left + rect.w - 1; x++) {
        if (tiles[y * width + x] === 'rock') continue
        tiles[y * width + x] = y === bridgeY ? 'bridge' : 'water'
      }
    }
  }

  // A ledge or two: a visible change of level, walkable, purely for texture.
  for (let i = 0; i < 2; i++) {
    const room = plan.rooms[rng.int(0, plan.rooms.length - 1)]
    const centre = centres[room.id]
    const x = centre.x + rng.int(-2, 2)
    const y = centre.y + rng.int(-1, 1)
    if (tileAt({ width, height, tiles, entrance: centre, exit: centre, roomCentres: centres, theme }, x, y) === 'floor') {
      tiles[y * width + x] = 'ledge'
    }
  }

  const entrance = centres[plan.entranceRoomId] ?? { x: 1, y: 1 }
  const exit = centres[plan.exitRoomId] ?? entrance
  tiles[exit.y * width + exit.x] = 'stairs'

  return { width, height, tiles, entrance, exit, roomCentres: centres, theme }
}

// ── Entities on the floor ──────────────────────────────────────────────────

export type EntityKind = 'encounter' | 'chest' | 'lucky'

export interface FloorEntity {
  readonly id: string
  readonly kind: EntityKind
  readonly at: TilePoint
  readonly speciesId?: number
  readonly level?: number
  readonly isAlpha?: boolean
  readonly rarity?: 'common' | 'rare' | 'veryRare'
  /** Cleared: defeated, captured, opened or taken. */
  taken: boolean
}

/**
 * Places what the floor plan says, on real tiles.
 *
 * APPROVED (§7, §8): encounters are **visible** and never aggro. Some sit in a
 * corridor and guard it, which is a reason to fight rather than an obligation:
 * there is usually another way round, and walking past one is allowed.
 */
export function placeEntities(plan: FloorPlan, tiles: FloorTiles, seed: number, luckyChance = 0.1): FloorEntity[] {
  const rng = streamFor(seed, 'entities', tiles.theme, plan.floor)
  const used = new Set<string>([`${tiles.entrance.x}:${tiles.entrance.y}`])
  const entities: FloorEntity[] = []

  const freeNear = (centre: TilePoint, spread: number): TilePoint => {
    for (let attempt = 0; attempt < 24; attempt++) {
      const x = centre.x + rng.int(-spread, spread)
      const y = centre.y + rng.int(-spread, spread)
      const key = `${x}:${y}`
      if (!used.has(key) && isWalkable(tiles, x, y) && tileAt(tiles, x, y) !== 'stairs') {
        used.add(key)
        return { x, y }
      }
    }
    return centre
  }

  for (const encounter of plan.encounters) {
    const centre = tiles.roomCentres[encounter.roomId] ?? tiles.entrance
    entities.push({
      id: encounter.id,
      kind: 'encounter',
      at: encounter.isAlpha ? centre : freeNear(centre, 2),
      speciesId: encounter.speciesId,
      level: encounter.level,
      isAlpha: encounter.isAlpha,
      taken: false,
    })
  }

  for (const chest of plan.chests) {
    const centre = tiles.roomCentres[chest.roomId] ?? tiles.entrance
    entities.push({ id: chest.id, kind: 'chest', at: freeNear(centre, 2), rarity: chest.rarity, taken: false })
  }

  // Lucky Pokémon: APPROVED CONCEPT, OPEN BALANCE. One per floor at most.
  if (rng.chance(luckyChance) && plan.encounters.length > 0) {
    const host = plan.encounters[rng.int(0, plan.encounters.length - 1)]
    const centre = tiles.roomCentres[host.roomId] ?? tiles.entrance
    entities.push({
      id: `${plan.floor}-lucky`, kind: 'lucky', at: freeNear(centre, 3),
      speciesId: host.speciesId, level: host.level, taken: false,
    })
  }

  return entities
}

/** Orthogonal neighbours, for "what can I interact with from here". */
export const isAdjacent = (a: TilePoint, b: TilePoint): boolean =>
  Math.abs(a.x - b.x) + Math.abs(a.y - b.y) === 1

export const samePoint = (a: TilePoint, b: TilePoint): boolean => a.x === b.x && a.y === b.y
