// From a floor plan to WildLands underground (D1 §6, rebuilt in D1.2.1).
//
// D1.2.1 changed the reference. It used to be "a Pokémon cave": rooms joined by
// one-tile corridors. It is now **WildLands put inside a cave**, so the floor is
// generated the way a stretch of overworld reads — open ground with shape, wide
// natural routes, water with a shore, patches of biome — and the room graph that
// still drives the rules is deliberately invisible in the result.
//
// The plan layer above (floorPlan.ts) is untouched: same seed, same definition,
// same floor, same rooms, same links, same encounters. Only the *spatial output*
// changed.
//
// D1.2.2 sends the last floor somewhere else entirely: a boss floor is a
// designed room (bossRoom.ts), not a procedural one.
//
// Deterministic from the floor's own seed, so the map a player sees can be
// regenerated by a server that has the seed.

import { streamFor, type Rng } from './rng'
import { buildBossRoom, isBossFloor } from './bossRoom'
import type { FloorPlan, FloorRoom } from './floorPlan'
import type { DungeonTheme } from './tiers'
import {
  CELL_TILES, isWalkable, MIN_CHAMBER, openWidth, PATH_WIDTH, tileAt, WALKABLE,
  type FloorTiles, type TileKind, type TilePoint,
} from './tileKinds'

// The vocabulary itself moved to tileKinds.ts in D1.2.2 so the Boss Room can
// share it without a circular import. It is re-exported here: this is still the
// module the rest of the prototype asks for a floor.
export {
  CELL_TILES, isWalkable, MIN_CHAMBER, openWidth, PATH_WIDTH, tileAt, WALKABLE,
  type FloorTiles, type TileKind, type TilePoint,
} from './tileKinds'

/** The decoration each biome paints over the same cave. */
export const THEME_LOOK: Readonly<Record<DungeonTheme, { accent: string; water: string; name: string }>> = {
  cave: { accent: '#6b7a99', water: '#2a4a6b', name: 'cueva' },
  mine: { accent: '#8a7a5a', water: '#33405c', name: 'cueva + mina' },
  glacier: { accent: '#bfe3ff', water: '#3a6d93', name: 'cueva + nieve' },
  forest: { accent: '#4c7a4a', water: '#2f5d55', name: 'cueva + bosque' },
  volcano: { accent: '#a5462c', water: '#7a2f18', name: 'cueva + volcánico' },
  ruin: { accent: '#9c8f72', water: '#35506b', name: 'cueva + ruinas' },
  tower: { accent: '#7b6fa8', water: '#3b3d72', name: 'cueva + cristales' },
}

// ── Carving ────────────────────────────────────────────────────────────────

interface Canvas {
  readonly tiles: TileKind[]
  readonly width: number
  readonly height: number
}

const inBounds = (canvas: Canvas, x: number, y: number): boolean =>
  x >= 1 && y >= 1 && x < canvas.width - 1 && y < canvas.height - 1

function put(canvas: Canvas, x: number, y: number, kind: TileKind): void {
  if (inBounds(canvas, x, y)) canvas.tiles[y * canvas.width + x] = kind
}

const read = (canvas: Canvas, x: number, y: number): TileKind =>
  x < 0 || y < 0 || x >= canvas.width || y >= canvas.height ? 'rock' : canvas.tiles[y * canvas.width + x]

/** A round patch of ground. Everything in the cave is made of these. */
function disc(canvas: Canvas, cx: number, cy: number, radius: number): void {
  const r2 = radius * radius
  for (let y = Math.floor(cy - radius); y <= Math.ceil(cy + radius); y++) {
    for (let x = Math.floor(cx - radius); x <= Math.ceil(cx + radius); x++) {
      const dx = x - cx
      const dy = (y - cy) * 1.15 // a touch wider than tall, like an eroded chamber
      if (dx * dx + dy * dy <= r2 && read(canvas, x, y) === 'rock') put(canvas, x, y, 'floor')
    }
  }
}

/**
 * A chamber: four to seven overlapping discs, so the outline is lumpy rock and
 * never a rectangle. This is what hides the room graph.
 */
function chamber(canvas: Canvas, centre: TilePoint, room: FloorRoom, rng: Rng): void {
  const base = Math.max(MIN_CHAMBER / 2, (room.w + room.h) * 0.95)
  disc(canvas, centre.x, centre.y, base)
  const lobes = rng.int(3, 6)
  for (let i = 0; i < lobes; i++) {
    const angle = (i / lobes) * Math.PI * 2 + rng.next() * 0.9
    const reach = base * (0.45 + rng.next() * 0.55)
    disc(canvas, centre.x + Math.cos(angle) * reach, centre.y + Math.sin(angle) * reach, base * (0.45 + rng.next() * 0.4))
  }
}

/**
 * A route: discs stamped along a line that wanders, so a passage reads as a
 * natural gallery rather than a corridor. The width is the clear ground the
 * route guarantees end to end.
 */
function route(canvas: Canvas, from: TilePoint, to: TilePoint, width: number, rng: Rng): void {
  const radius = width / 2
  const span = Math.hypot(to.x - from.x, to.y - from.y)
  const steps = Math.max(2, Math.round(span / 2))
  // Two control points pull the line off the straight run between the rooms.
  const sway = Math.min(9, span * 0.22)
  const swing = () => (rng.next() - 0.5) * sway * 2
  const a = { x: from.x + (to.x - from.x) / 3 + swing(), y: from.y + (to.y - from.y) / 3 + swing() }
  const b = { x: from.x + ((to.x - from.x) * 2) / 3 + swing(), y: from.y + ((to.y - from.y) * 2) / 3 + swing() }
  for (let i = 0; i <= steps; i++) {
    const t = i / steps
    const u = 1 - t
    // Cubic Bézier through the two control points.
    const x = u * u * u * from.x + 3 * u * u * t * a.x + 3 * u * t * t * b.x + t * t * t * to.x
    const y = u * u * u * from.y + 3 * u * u * t * a.y + 3 * u * t * t * b.y + t * t * t * to.y
    // The width breathes a little, but never below what the route promises.
    disc(canvas, x, y, radius + rng.next() * 1.2)
  }
}

/** Gravel and biome patches scattered over ground that is already carved. */
function weather(canvas: Canvas, centre: TilePoint, spread: number, rng: Rng, kind: TileKind, patches: number): void {
  for (let i = 0; i < patches; i++) {
    const x = centre.x + Math.round((rng.next() - 0.5) * spread * 2)
    const y = centre.y + Math.round((rng.next() - 0.5) * spread * 2)
    const radius = 1 + rng.next() * 2.4
    for (let py = Math.floor(y - radius); py <= Math.ceil(y + radius); py++) {
      for (let px = Math.floor(x - radius); px <= Math.ceil(x + radius); px++) {
        const dx = px - x
        const dy = py - y
        if (dx * dx + dy * dy > radius * radius) continue
        if (read(canvas, px, py) === 'floor') put(canvas, px, py, kind)
      }
    }
  }
}

const cellCentre = (room: FloorRoom, rng: Rng): TilePoint => ({
  x: room.gx * CELL_TILES.w + Math.round(CELL_TILES.w / 2) + rng.int(-3, 3),
  y: room.gy * CELL_TILES.h + Math.round(CELL_TILES.h / 2) + rng.int(-2, 2),
})

export function buildFloorTiles(plan: FloorPlan, theme: DungeonTheme, seed: number): FloorTiles {
  // D1.2.2 §9: the boss floor is a designed room, not a procedural one.
  if (plan.difficulty.isBossFloor) return buildBossRoom(plan, theme, seed)
  const rng = streamFor(seed, 'tiles', theme, plan.floor)
  const width = (plan.width + 1) * CELL_TILES.w
  const height = (plan.height + 1) * CELL_TILES.h
  const canvas: Canvas = { tiles: new Array<TileKind>(width * height).fill('rock'), width, height }

  const centres: Record<number, TilePoint> = {}
  for (const room of plan.rooms) centres[room.id] = cellCentre(room, rng)

  // 1. Routes first, so chambers open onto ground that is already there and a
  //    seam never reads as "a corridor arriving at a door".
  for (const link of plan.links) {
    const from = centres[link.from]
    const to = centres[link.to]
    if (!from || !to) continue
    // The spine is the chain the generator walked; branches hang off it.
    const main = link.to === link.from + 1
    route(canvas, from, to, main ? PATH_WIDTH.main : PATH_WIDTH.side, rng)
  }

  // 2. Extra loops: a second way round, so a Pokémon in a passage is a reason to
  //    fight and not a wall (§6).
  const loops = Math.max(1, Math.round(plan.rooms.length / 4))
  for (let i = 0; i < loops; i++) {
    const a = plan.rooms[rng.int(0, plan.rooms.length - 1)]
    const b = plan.rooms.find(room => room.id !== a.id
      && Math.abs(room.gx - a.gx) + Math.abs(room.gy - a.gy) === 1
      && !plan.links.some(link => (link.from === a.id && link.to === room.id) || (link.from === room.id && link.to === a.id)))
    if (b) route(canvas, centres[a.id], centres[b.id], PATH_WIDTH.side, rng)
  }

  // 3. Chambers.
  for (const room of plan.rooms) chamber(canvas, centres[room.id], room, rng)

  // 4. The floor's own texture: gravel and patches of whatever biome grew here.
  for (const room of plan.rooms) {
    const centre = centres[room.id]
    weather(canvas, centre, 9, rng, 'rubble', rng.int(1, 3))
    weather(canvas, centre, 10, rng, 'accent', rng.int(1, 4))
  }

  // 5. Water: a lake in one chamber with a bridge across it. The bridge is a
  //    deliberate pinch point (§8), and the only one the generator guarantees.
  if (plan.rooms.length > 3 && rng.chance(0.45 + plan.difficulty.depth * 0.3)) {
    const room = plan.rooms[rng.int(1, plan.rooms.length - 1)]
    const centre = centres[room.id]
    const radius = 4 + rng.next() * 3
    for (let y = Math.floor(centre.y - radius); y <= Math.ceil(centre.y + radius); y++) {
      for (let x = Math.floor(centre.x - radius); x <= Math.ceil(centre.x + radius); x++) {
        const dx = x - centre.x
        const dy = (y - centre.y) * 1.25
        if (dx * dx + dy * dy > radius * radius) continue
        if (WALKABLE.has(read(canvas, x, y))) put(canvas, x, y, 'water')
      }
    }
    const half = Math.floor(PATH_WIDTH.pinch / 2)
    for (let y = Math.floor(centre.y - radius) - 2; y <= Math.ceil(centre.y + radius) + 2; y++) {
      for (let dx = -half; dx <= half; dx++) {
        if (read(canvas, centre.x + dx, y) === 'water') put(canvas, centre.x + dx, y, 'bridge')
      }
    }
  }

  // 6. A ledge or two: a visible change of level, walkable, purely for texture.
  for (let i = 0; i < 3; i++) {
    const room = plan.rooms[rng.int(0, plan.rooms.length - 1)]
    const centre = centres[room.id]
    const x = centre.x + rng.int(-5, 5)
    const y = centre.y + rng.int(-3, 3)
    if (read(canvas, x, y) === 'floor') put(canvas, x, y, 'ledge')
  }

  // 6.5 A lake can cut a chamber off from the route that fed it. Rather than
  //     forbid lakes, the floor is repaired: anything the entrance cannot reach
  //     gets a new gallery carved to it, with the same tool and the same width,
  //     so the fix is invisible.
  connect(canvas, plan, centres, rng)

  // 7. Where the player arrives and where the way down is. Both want room around
  //    them (§13), so each takes the most open tile its chamber has.
  const draft: FloorTiles = {
    width, height, tiles: canvas.tiles, roomCentres: centres, theme,
    entrance: centres[plan.entranceRoomId] ?? { x: 1, y: 1 },
    exit: centres[plan.exitRoomId] ?? { x: 1, y: 1 },
  }
  const entrance = openSpot(draft, draft.entrance)
  const exit = openSpot(draft, draft.exit)
  put(canvas, exit.x, exit.y, 'stairs')

  return { ...draft, entrance, exit }
}

/** The nearest tile to `centre` a party could actually stand on. */
function footing(canvas: Canvas, centre: TilePoint): TilePoint | null {
  for (let radius = 0; radius <= 8; radius++) {
    for (let dy = -radius; dy <= radius; dy++) {
      for (let dx = -radius; dx <= radius; dx++) {
        if (Math.max(Math.abs(dx), Math.abs(dy)) !== radius) continue
        const spot = { x: centre.x + dx, y: centre.y + dy }
        const kind = read(canvas, spot.x, spot.y)
        if (WALKABLE.has(kind) && kind !== 'bridge') return spot
      }
    }
  }
  return null
}

/** Everything walkable that can be reached on foot from `start`. */
function reach(canvas: Canvas, start: TilePoint): Set<number> {
  const seen = new Set<number>([start.y * canvas.width + start.x])
  const queue = [start]
  while (queue.length) {
    const at = queue.shift()!
    for (const [dx, dy] of [[0, 1], [0, -1], [1, 0], [-1, 0]]) {
      const x = at.x + dx
      const y = at.y + dy
      const key = y * canvas.width + x
      if (seen.has(key) || !WALKABLE.has(read(canvas, x, y))) continue
      seen.add(key)
      queue.push({ x, y })
    }
  }
  return seen
}

/**
 * Carves galleries until every chamber can be walked to from the first one.
 * Water is the usual culprit: a lake can swallow the passage that fed a room.
 */
function connect(canvas: Canvas, plan: FloorPlan, centres: Record<number, TilePoint>, rng: Rng): void {
  const anchors = new Map<number, TilePoint>()
  for (const room of plan.rooms) {
    const spot = footing(canvas, centres[room.id])
    if (spot) anchors.set(room.id, spot)
  }
  const home = anchors.get(plan.entranceRoomId) ?? anchors.values().next().value
  if (!home) return

  for (let pass = 0; pass < 6; pass++) {
    const reached = reach(canvas, home)
    const lost = [...anchors].filter(([, spot]) => !reached.has(spot.y * canvas.width + spot.x))
    if (!lost.length) return
    for (const [id, spot] of lost) {
      const nearest = [...anchors]
        .filter(([other]) => other !== id && reached.has(anchors.get(other)!.y * canvas.width + anchors.get(other)!.x))
        .sort(([, a], [, b]) => Math.hypot(a.x - spot.x, a.y - spot.y) - Math.hypot(b.x - spot.x, b.y - spot.y))[0]
      if (!nearest) continue
      route(canvas, nearest[1], spot, PATH_WIDTH.side, rng)
    }
  }
}

/** The most open walkable tile near `centre`: what a stairway or a spawn wants. */
function openSpot(tiles: FloorTiles, centre: TilePoint): TilePoint {
  let best = centre
  let bestScore = -1
  for (let dy = -4; dy <= 4; dy++) {
    for (let dx = -5; dx <= 5; dx++) {
      const x = centre.x + dx
      const y = centre.y + dy
      // A spawn or a stairway never sits on a bridge: it is a pinch point, and a
      // landing cut into planks over water makes no sense (§13).
      if (!isWalkable(tiles, x, y) || tileAt(tiles, x, y) === 'bridge') continue
      let open = 0
      for (let ny = -2; ny <= 2; ny++) for (let nx = -2; nx <= 2; nx++) if (isWalkable(tiles, x + nx, y + ny)) open++
      const score = open - (Math.abs(dx) + Math.abs(dy)) * 0.25
      if (score > bestScore) {
        bestScore = score
        best = { x, y }
      }
    }
  }
  return best
}

/** Walkable tiles that touch rock: where a chest or a prop belongs (§13). */
export function wallSpots(tiles: FloorTiles, centre: TilePoint, spread: number): TilePoint[] {
  const out: TilePoint[] = []
  for (let dy = -spread; dy <= spread; dy++) {
    for (let dx = -spread; dx <= spread; dx++) {
      const x = centre.x + dx
      const y = centre.y + dy
      const kind = tileAt(tiles, x, y)
      if (!WALKABLE.has(kind) || kind === 'stairs' || kind === 'bridge') continue
      const walls = [[0, -1], [0, 1], [-1, 0], [1, 0]].filter(([ox, oy]) => !isWalkable(tiles, x + ox, y + oy)).length
      // Against a wall, ideally in a nook — but never plugging a narrow pass.
      if (walls >= 1 && walls <= 2 && openWidth(tiles, x, y) > PATH_WIDTH.pinch) out.push({ x, y })
    }
  }
  return out
}

// ── Entities on the floor ──────────────────────────────────────────────────

export type EntityKind = 'encounter' | 'chest' | 'lucky'

export interface FloorEntity {
  readonly id: string
  readonly kind: EntityKind
  readonly at: TilePoint
  readonly speciesId?: number
  readonly level?: number
  readonly isAlpha?: boolean
  readonly rarity?: 'common' | 'rare' | 'veryRare'
  /** Cleared: defeated, captured, opened or taken. */
  taken: boolean
}

/**
 * Places what the floor plan says, on real tiles.
 *
 * APPROVED (D1 §7, §8): encounters are **visible** and never aggro. D1.2.1 §6
 * adds that they must not be a wall either: a Pokémon goes on ground wide
 * enough for a party to walk around it.
 */
export function placeEntities(plan: FloorPlan, tiles: FloorTiles, seed: number, luckyChance = 0.1): FloorEntity[] {
  const rng = streamFor(seed, 'entities', tiles.theme, plan.floor)
  const used = new Set<string>([`${tiles.entrance.x}:${tiles.entrance.y}`])
  const entities: FloorEntity[] = []

  /** Open ground: a Pokémon standing here still leaves a way past. */
  const freeNear = (centre: TilePoint, spread: number): TilePoint => {
    let fallback: TilePoint | null = null
    for (let attempt = 0; attempt < 48; attempt++) {
      const x = centre.x + rng.int(-spread, spread)
      const y = centre.y + rng.int(-spread, spread)
      const key = `${x}:${y}`
      if (used.has(key) || !isWalkable(tiles, x, y) || tileAt(tiles, x, y) === 'stairs') continue
      if (!fallback) fallback = { x, y }
      if (openWidth(tiles, x, y) <= PATH_WIDTH.pinch + 1) continue
      used.add(key)
      return { x, y }
    }
    if (fallback) used.add(`${fallback.x}:${fallback.y}`)
    return fallback ?? centre
  }

  /** Against a wall, in a nook, out of the traffic (§13). */
  const nookNear = (centre: TilePoint, spread: number): TilePoint => {
    const spots = wallSpots(tiles, centre, spread).filter(spot => !used.has(`${spot.x}:${spot.y}`))
    if (!spots.length) return freeNear(centre, spread)
    const pick = spots[rng.int(0, spots.length - 1)]
    used.add(`${pick.x}:${pick.y}`)
    return pick
  }

  for (const encounter of plan.encounters) {
    const centre = tiles.roomCentres[encounter.roomId] ?? tiles.entrance
    entities.push({
      id: encounter.id,
      kind: 'encounter',
      // D1.2.2 §14: the Alpha has its own spot in the Boss Room. It is never on
      // the way out and never where a player arrives.
      at: encounter.isAlpha
        ? (isBossFloor(tiles) ? tiles.boss.alpha : tiles.exit)
        : freeNear(centre, 6),
      speciesId: encounter.speciesId,
      level: encounter.level,
      isAlpha: encounter.isAlpha,
      taken: false,
    })
  }

  for (const chest of plan.chests) {
    const centre = tiles.roomCentres[chest.roomId] ?? tiles.entrance
    entities.push({ id: chest.id, kind: 'chest', at: nookNear(centre, 8), rarity: chest.rarity, taken: false })
  }

  // Lucky Pokémon: APPROVED CONCEPT, OPEN BALANCE. One per floor at most.
  if (rng.chance(luckyChance) && plan.encounters.length > 0) {
    const host = plan.encounters[rng.int(0, plan.encounters.length - 1)]
    const centre = tiles.roomCentres[host.roomId] ?? tiles.entrance
    entities.push({
      id: `${plan.floor}-lucky`, kind: 'lucky', at: freeNear(centre, 7),
      speciesId: host.speciesId, level: host.level, taken: false,
    })
  }

  return entities
}

/** Orthogonal neighbours, for "what can I interact with from here". */
export const isAdjacent = (a: TilePoint, b: TilePoint): boolean =>
  Math.abs(a.x - b.x) + Math.abs(a.y - b.y) === 1

export const samePoint = (a: TilePoint, b: TilePoint): boolean => a.x === b.x && a.y === b.y
