// What PokeSwap has today, seen as Pokémon (R32.2).
//
// The audit's finding, first, because everything here follows from it:
// **PokeSwap has no per-individual Pokémon.** It has
//
//   `slots`       one row per *species* (`pokemon_id`), with a single global
//                 owner, a price, an aura and an energy. Two players cannot own
//                 Pikachu; there is one Pikachu.
//   `pokemon_xp`  one row per (user, species): xp, a level recomputed from it
//                 by `grant_pokemon_xp`, and a `moves` JSON blob.
//   `swap_history.was_shiny`  the only place shininess is ever recorded, and it
//                 describes an event, not a Pokémon.
//
// So there is nothing to migrate in the usual sense: nature, IVs, EVs, gender,
// form and PP **do not exist** in production and cannot be recovered from it.
//
// This file therefore does one honest thing: it *projects* a legacy row into
// the part of a `PokemonInstance` that is genuinely known — species, level and
// experience, owner, and the moves that can be resolved — and reports
// everything that is missing instead of inventing it. Nothing here writes, and
// nothing here is wired to production: the backfill strategy is a proposal in
// `docs/wildlands/POKEMON_SPECIES_INSTANCE_MODEL.md` awaiting approval.

import type { PokemonCatalogView } from './catalogView'
import legacyMoves from './generated/legacyMoves.json'
import { levelForExperience } from './experience'
import type { MoveSlot, PokemonInstanceDraft, SpeciesId } from './instance'
import { INSTANCE_SCHEMA_VERSION, MAX_MOVE_SLOTS } from './instance'
import { ZERO_STATS } from './stats'

/**
 * The canonicalization layer, generated by `scripts/legacy-move-audit.mjs` from
 * the legacy tables themselves plus one documented historical rename. It is
 * regenerated, never edited: see `docs/wildlands/LEGACY_MOVE_AUDIT.md`.
 */
const CANONICAL_MOVE_IDS: Readonly<Record<string, number>> = legacyMoves.aliases

/** Slugs a pinned source proves were introduced after Generation VI. */
const INCOMPATIBLE_MOVES: Readonly<Record<string, number>> = legacyMoves.incompatible

/** Which catalog and which legacy snapshot the two tables above were built from. */
export const LEGACY_MOVE_TABLES = {
  catalogVersion: legacyMoves.catalogVersion,
  legacyTag: legacyMoves.legacyTag,
  legacyCommit: legacyMoves.legacyCommit,
  canonicalCount: Object.keys(legacyMoves.aliases).length,
  incompatibleCount: Object.keys(legacyMoves.incompatible).length,
} as const

/** The legacy rows this adapter reads, narrowed to what it actually needs. */
export interface LegacySlotRow {
  readonly pokemon_id: number
  readonly owner_id: string | null
  readonly first_owner_id?: string | null
  readonly owned_since?: string | null
}

export interface LegacyXpRow {
  readonly user_id: string
  readonly pokemon_id: number
  readonly xp: number
  readonly level: number
  readonly moves: Record<string, unknown> | null
}

/** A field the legacy data cannot answer, and how the projection filled it. */
export interface LegacyGap {
  readonly field: 'natureId' | 'abilityId' | 'ivs' | 'evs' | 'gender' | 'shiny' | 'moves' | 'formId'
  readonly reason: string
}

export interface LegacyProjection {
  /**
   * The instance as far as the data supports it, **minus** every field the
   * legacy rows cannot answer. It is deliberately not a `PokemonInstanceDraft`:
   * a partial record cannot be mistaken for a Pokémon that is ready to persist.
   */
  readonly known: LegacyKnown
  /** Everything a backfill would have to decide, in the words of the doc. */
  readonly gaps: readonly LegacyGap[]
  /** Rows that do not line up with the catalog at all. */
  readonly problems: readonly string[]
  /** Every legacy move slug that did not become a move, with its reason. */
  readonly unresolvedMoves: readonly LegacyMoveProblem[]
}

export type LegacyKnown = Pick<
  PokemonInstanceDraft,
  'schemaVersion' | 'speciesId' | 'experience' | 'ownership' | 'state' | 'nickname'
> & {
  /** Derived from `experience`, exposed because the legacy row also stores it. */
  readonly level: number
  /** Only the moves that resolve against the catalog by name or id. */
  readonly moves: readonly MoveSlot[]
  /** True when the row's stored level disagrees with its own xp. */
  readonly levelDisagrees: boolean
  /** The `pokemon_xp` row's user: whose training this is, not who owns it. */
  readonly progressionTrainerId: string
}

const ALWAYS_MISSING: readonly LegacyGap[] = [
  { field: 'natureId', reason: 'production has never stored a nature' },
  { field: 'abilityId', reason: 'production has never stored an ability' },
  { field: 'ivs', reason: 'production has never stored IVs' },
  { field: 'evs', reason: 'production has never stored EVs' },
  { field: 'gender', reason: 'production has never stored a gender' },
  { field: 'shiny', reason: 'shininess exists only on swap_history rows, per event' },
]

/**
 * Projects the progression of one Pokémon: a `pokemon_xp` row, read as the
 * training the **slot's current owner** did on it.
 *
 * Ownership comes from `options.slot.owner_id` and from nowhere else. A
 * `pokemon_xp` row identifies whose training it is, not who owns the Pokémon:
 * rows of former owners describe history, and passing one here without its slot
 * yields a projection with no owner rather than a second Pokémon.
 *
 * It never guesses. Where the legacy data is silent the field is absent from
 * `known` and named in `gaps`, so a caller cannot accidentally persist a
 * Pokémon whose nature was made up by an adapter.
 */
export function projectLegacyPokemon(
  xp: LegacyXpRow,
  catalog: PokemonCatalogView,
  options: { readonly slot?: LegacySlotRow | null } = {},
): LegacyProjection {
  const problems: string[] = []
  const speciesId: SpeciesId = xp.pokemon_id
  const species = catalog.speciesOf(speciesId)
  if (!species) problems.push(`species ${speciesId} is not in the Battle Catalog`)

  const level = levelForExperience(xp.xp)
  const levelDisagrees = Number.isFinite(xp.level) && xp.level !== level
  if (levelDisagrees) problems.push(`stored level ${xp.level} but ${xp.xp} xp is level ${level}`)

  const { moves, unresolved } = readLegacyMoves(xp.moves, catalog)
  for (const problem of unresolved) {
    problems.push(problem.kind === 'incompatible'
      ? `move ${problem.slug} does not exist in ORAS (generation ${problem.generation})`
      : `move ${problem.slug} cannot be identified`)
  }

  const gaps: LegacyGap[] = [...ALWAYS_MISSING]
  const defaultForm = catalog.defaultForm(speciesId)
  if (!defaultForm) {
    gaps.push({ field: 'formId', reason: 'the species has no default form in the catalog' })
  }
  if (moves.length === 0) {
    gaps.push({ field: 'moves', reason: 'the row carries no move this catalog recognises' })
  }

  // slots.owner_id is the only source of truth for ownership (R32.2.1).
  const ownerId = options.slot?.owner_id ?? null
  if (options.slot && options.slot.owner_id !== null && options.slot.owner_id !== xp.user_id) {
    problems.push(`progression belongs to ${xp.user_id}, who no longer owns this slot`)
  }
  const known: LegacyKnown = {
    schemaVersion: INSTANCE_SCHEMA_VERSION,
    speciesId,
    experience: Math.max(0, Math.floor(xp.xp)),
    level,
    moves,
    ownership: {
      ownerId,
      originalTrainerId: options.slot?.first_owner_id ?? null,
    },
    /** Whose training this is. Metadata for the audit; never ownership. */
    progressionTrainerId: xp.user_id,
    state: 'owned',
    nickname: null,
    levelDisagrees,
  }
  return { known, gaps, problems, unresolvedMoves: unresolved }
}

/** Why a legacy move slug could not become a move of this catalog. */
export type LegacyMoveProblemKind =
  /** The move genuinely does not exist in ORAS: it was introduced later. */
  | 'incompatible'
  /** It cannot be identified at all with the sources R32.1 pinned. */
  | 'unknown'

export interface LegacyMoveProblem {
  readonly slug: string
  readonly kind: LegacyMoveProblemKind
  /** The generation that introduced it, when a pinned source proves one. */
  readonly generation?: number
}

/**
 * Reads the legacy `moves` blob.
 *
 * Its shape is not guaranteed — more than one version of the game wrote it — so
 * this accepts the two forms seen in the data (a list, or an object keyed by
 * slot) and resolves each entry three ways, in order: a numeric catalog id, an
 * exact catalog identifier, and the **canonicalization map** (R32.2.1).
 *
 * The map is what keeps `latigo-cepa` and `vise-grip` from being treated as
 * losses: they are the same moves as `vine-whip` and `vice-grip`, written the
 * way the old game wrote them, and recognising them is not a backfill. What
 * cannot be recognised is reported with its reason, never replaced.
 */
export function readLegacyMoves(
  blob: Record<string, unknown> | null,
  catalog: PokemonCatalogView,
): { moves: readonly MoveSlot[]; unresolved: readonly LegacyMoveProblem[] } {
  if (!blob) return { moves: [], unresolved: [] }
  const raw: unknown[] = Array.isArray(blob) ? blob : Object.values(blob)
  const moves: MoveSlot[] = []
  const unresolved: LegacyMoveProblem[] = []
  for (const entry of raw) {
    const id = resolveMoveId(entry, catalog)
    if (id === null) { unresolved.push(describeProblem(entry)); continue }
    if (moves.some(slot => slot.moveId === id)) continue
    moves.push({ moveId: id, ppUps: 0 })
  }
  return { moves: moves.slice(0, MAX_MOVE_SLOTS), unresolved }
}

/** The slug a legacy entry carries, normalised the way the old game wrote it. */
export function legacySlugOf(entry: unknown): string | null {
  const value = typeof entry === 'object' && entry !== null
    ? ((entry as Record<string, unknown>).id ?? (entry as Record<string, unknown>).name)
    : entry
  if (typeof value !== 'string') return null
  const slug = value.trim().toLowerCase().replace(/[\s_]+/g, '-')
  return slug === '' ? null : slug
}

/** The canonical move id of a legacy slug, or null when it is not one move of ORAS. */
export function canonicalMoveId(slug: string, catalog: PokemonCatalogView): number | null {
  const exact = catalog.moveNamed(slug)
  if (exact) return exact.id
  const canonical = CANONICAL_MOVE_IDS[slug]
  return canonical !== undefined && catalog.move(canonical) ? canonical : null
}

function resolveMoveId(entry: unknown, catalog: PokemonCatalogView): number | null {
  const value = typeof entry === 'object' && entry !== null
    ? ((entry as Record<string, unknown>).id ?? (entry as Record<string, unknown>).name)
    : entry
  if (typeof value === 'number' && catalog.move(value)) return value
  const slug = legacySlugOf(entry)
  if (slug !== null) {
    const id = canonicalMoveId(slug, catalog)
    if (id !== null) return id
    const numeric = Number(slug)
    if (Number.isInteger(numeric) && catalog.move(numeric)) return numeric
  }
  return null
}

function describeProblem(entry: unknown): LegacyMoveProblem {
  const slug = legacySlugOf(entry) ?? describe(entry)
  const generation = INCOMPATIBLE_MOVES[slug]
  return generation !== undefined
    ? { slug, kind: 'incompatible', generation }
    : { slug, kind: 'unknown' }
}

const describe = (entry: unknown): string =>
  typeof entry === 'object' && entry !== null ? JSON.stringify(entry) : String(entry)

/** The EVs a migrated Pokémon starts with under every proposal: none. */
export const MIGRATION_EVS = ZERO_STATS
