// The move effect registry (R32.3).
//
// There is no `if (moveId === 25)` anywhere in these rules, and there is not
// going to be: 621 moves cannot be a switch over identifiers. Behaviour is
// resolved from the move's **`effectId`** — PokeSwap's own classification,
// generated by R32.1 from structured columns — plus its `meta`. Adding a move
// to the catalog adds it to the game; it does not add a branch here.
//
// What a move may do is deliberately small and composable: damage, multi-hit,
// drain, recoil, recharge, a major status, confusion, a heal, a shield. A move
// whose effect is not in that list is **refused with a reason** (`moveSupport`)
// rather than run as a plain hit. An honest gap beats a move that looks like
// it worked.
//
// The order of the rolls is part of the contract, because a replay depends on
// it: accuracy, then the hit count, then per hit a crit and a spread, then the
// secondary chance. A move that cannot miss still spends its accuracy draw, so
// adding one later cannot shift every roll after it.

import type { CatalogMove } from '../catalog'
import { cooldownAfterMove } from './actionBar'
import { computeDamage, rollAccuracy, rollHitCount } from './damage'
import { classifyMove, isMajorStatusAilment } from './moveSupport'
import type { SupportedEffect } from './moveSupport'
import { drawChance } from './rng'
import type { BattleCombatant, StageKey } from './state'
import { isCombatantFainted, opposingActive, withRuntime } from './state'
import {
  applyConfusion, applyDamage, applyHeal, applyMajorStatus, emit, modifyStat, requireCombatant,
  spendPp, update,
} from './transitions'
import type { Working } from './transitions'

/** The move a Pokémon is left with when nothing else has PP (§22). */
export const STRUGGLE_MOVE_NAME = 'struggle'

/**
 * A move counts as offensive — and so is absorbed by Protect — when it is
 * aimed at somebody else. A buff or a heal is not something to shield from.
 */
const isOffensive = (move: CatalogMove): boolean => move.target !== 'user'

const typesOfActiveForm = (working: Working, combatant: BattleCombatant) =>
  working.catalog.typesOf(combatant.runtime.activeFormId) ?? []

/**
 * Runs one move for one combatant. Returns nothing: everything it did is in
 * the events, and everything it changed is in `working.state`.
 *
 * `asStruggle` is how §22's fallback stays explicit. Struggle spends no PP,
 * ignores typing entirely (Gen VI) and costs its user a quarter of its own max
 * HP — of its **max** HP, not of the damage it dealt.
 */
export function executeMove(
  working: Working, attackerId: string, moveId: number, asStruggle: boolean,
): void {
  const attacker = requireCombatant(working, attackerId)
  if (!attacker) return
  const move = working.catalog.move(moveId)
  if (!move) {
    emit(working, { type: 'MOVE_REFUSED', combatantId: attackerId, moveId, refusal: { kind: 'unknownMove' } })
    return
  }
  const verdict = classifyMove(move)
  if (verdict.kind === 'deferred') {
    emit(working, {
      type: 'MOVE_REFUSED', combatantId: attackerId, moveId,
      refusal: { kind: 'deferred', reason: verdict.reason },
    })
    return
  }
  if (!asStruggle && !attacker.instance.moves.some(slot => slot.moveId === moveId)) {
    emit(working, { type: 'MOVE_REFUSED', combatantId: attackerId, moveId, refusal: { kind: 'notLearnt' } })
    return
  }
  if (!asStruggle && !spendPp(working, attackerId, moveId)) {
    emit(working, { type: 'MOVE_REFUSED', combatantId: attackerId, moveId, refusal: { kind: 'noPp' } })
    return
  }

  // Whatever happens next, this is now the move it used last, and this is what
  // its next Action Window costs.
  const afterPp = requireCombatant(working, attackerId)
  if (afterPp) {
    update(working, withRuntime(afterPp, {
      lastMoveId: asStruggle ? null : moveId,
      cooldownMultiplier: cooldownAfterMove(move.priority, move.effectId === 'damage.recharge', working.state.config),
    }))
  }

  const target = move.target === 'user' ? attacker : opposingActive(working.state, attackerId)
  if (!target) {
    emit(working, { type: 'MOVE_REFUSED', combatantId: attackerId, moveId, refusal: { kind: 'noTarget' } })
    return
  }

  // Protect answers before anything else: it is a shield, not a dodge, so the
  // move is spent and the accuracy roll never happens.
  if (isOffensive(move) && target.runtime.protectCharges > 0) {
    blockWithProtect(working, target.combatantId, attackerId, moveId)
    return
  }

  emit(working, {
    type: 'MOVE_USED', combatantId: attackerId, moveId,
    targetId: move.target === 'user' ? attackerId : target.combatantId, hits: 1,
  })

  switch (verdict.effect) {
    case 'protect':
      gainProtect(working, attackerId)
      return
    case 'heal':
      applyHeal(working, attackerId, Math.floor((attacker.stats.hp * (move.meta.healing ?? 0)) / 100), 'move')
      return
    case 'ailment':
      runStatusMove(working, attackerId, target.combatantId, move)
      return
    case 'statChange':
      runStatChangeMove(working, attackerId, target.combatantId, move)
      return
    default:
      runDamagingMove(working, attackerId, target.combatantId, move, verdict.effect, asStruggle)
  }
}

// ── Stat changes ────────────────────────────────────────────────────────────

/**
 * Applies a move's stat change, read entirely from the catalog.
 *
 * There is no branch per move: `meta.statChanges` says who, which stat, how
 * many stages and how often, and the pipeline only fills it in when its two
 * pinned sources settle all four (`statChanges.mjs`). Swords Dance, Growl and
 * Shadow Ball's secondary all come through here as data.
 */
function applyStatChanges(
  working: Working, attackerId: string, targetId: string, move: CatalogMove,
): void {
  const spec = move.meta.statChanges
  if (!spec) return
  const recipientId = spec.recipient === 'user' ? attackerId : targetId
  for (const change of spec.changes) {
    modifyStat(working, recipientId, change.stat as StageKey, change.stages, attackerId)
  }
}

/** A move whose whole point is the stat change: Swords Dance, Growl, Screech. */
function runStatChangeMove(
  working: Working, attackerId: string, targetId: string, move: CatalogMove,
): void {
  const attacker = requireCombatant(working, attackerId)
  const target = requireCombatant(working, targetId)
  if (!attacker || !target) return

  const accuracy = rollAccuracy(move.accuracy, attacker, target, working.state.config, working.state.rng)
  working.state = { ...working.state, rng: accuracy.rng }
  if (!accuracy.hit) {
    emit(working, { type: 'MOVE_MISSED', combatantId: attackerId, moveId: move.id })
    return
  }
  // Deliberately no type check: in Generation VI a Growl lowers a Ghost's
  // Attack. Only the damaging moves and Thunder Wave answer to the chart.
  applyStatChanges(working, attackerId, targetId, move)
}

// ── Protect ─────────────────────────────────────────────────────────────────

/**
 * Raises the shield — unless one is already up.
 *
 * Auto-repeat keeps a move selected, so without this a Pokémon that chose
 * Protect once would top its shield back up every Action Window and never be
 * hit again. The attempt is not free and it is not silent: the window and the
 * PP are already spent by the time we get here, and the failure is an event.
 *
 * What this deliberately is **not** is the games' falling success rate for
 * consecutive Protects. That is balance, and it is a later decision.
 */
function gainProtect(working: Working, combatantId: string): void {
  const combatant = requireCombatant(working, combatantId)
  if (!combatant) return
  if (combatant.runtime.protectCharges > 0) {
    emit(working, {
      type: 'PROTECT_FAILED', combatantId, chargesLeft: combatant.runtime.protectCharges,
    })
    return
  }
  const charges = working.state.config.protect.charges
  update(working, withRuntime(combatant, { protectCharges: charges }))
  emit(working, { type: 'PROTECT_GAINED', combatantId, charges })
}

/**
 * One offensive action absorbed. A multi-hit move spends **one** charge, not
 * one per hit (§23): the shield stops the action, not the animation.
 *
 * When the last charge goes, the shield's user pays for it with time: its next
 * Action Window is doubled.
 */
function blockWithProtect(
  working: Working, defenderId: string, attackerId: string, moveId: number,
): void {
  const defender = requireCombatant(working, defenderId)
  if (!defender) return
  const left = defender.runtime.protectCharges - 1
  update(working, withRuntime(defender, { protectCharges: Math.max(0, left) }))
  emit(working, {
    type: 'PROTECT_BLOCKED', combatantId: defenderId, sourceId: attackerId, moveId, chargesLeft: Math.max(0, left),
  })
  if (left <= 0) {
    const spent = requireCombatant(working, defenderId)
    if (spent) {
      update(working, withRuntime(spent, {
        cooldownMultiplier: working.state.config.actionBar.protectExpiryMultiplier,
      }))
    }
    emit(working, { type: 'PROTECT_EXPIRED', combatantId: defenderId })
  }
}

// ── Status moves ────────────────────────────────────────────────────────────

function runStatusMove(
  working: Working, attackerId: string, targetId: string, move: CatalogMove,
): void {
  const attacker = requireCombatant(working, attackerId)
  const target = requireCombatant(working, targetId)
  if (!attacker || !target) return

  const accuracy = rollAccuracy(move.accuracy, attacker, target, working.state.config, working.state.rng)
  working.state = { ...working.state, rng: accuracy.rng }
  if (!accuracy.hit) {
    emit(working, { type: 'MOVE_MISSED', combatantId: attackerId, moveId: move.id })
    return
  }

  const ailment = move.meta.ailment ?? 'none'
  if (ailment !== 'confusion' && !isMajorStatusAilment(ailment)) return

  // A status move still answers to the type chart: Thunder Wave does not
  // paralyse a Ground type, and an immunity is an immunity.
  const types = typesOfActiveForm(working, target)
  if (working.catalog.effectiveness(move.type, types) === 0) {
    emit(working, { type: 'STATUS_FAILED', combatantId: targetId, status: ailment, reason: 'missed' })
    return
  }

  if (ailment === 'confusion') applyConfusion(working, targetId)
  else applyMajorStatus(working, targetId, ailment, attackerId)
}

// ── Damaging moves ──────────────────────────────────────────────────────────

function runDamagingMove(
  working: Working,
  attackerId: string,
  targetId: string,
  move: CatalogMove,
  effect: SupportedEffect,
  asStruggle: boolean,
): void {
  const attacker = requireCombatant(working, attackerId)
  const target = requireCombatant(working, targetId)
  if (!attacker || !target) return

  const accuracy = rollAccuracy(move.accuracy, attacker, target, working.state.config, working.state.rng)
  working.state = { ...working.state, rng: accuracy.rng }
  if (!accuracy.hit) {
    emit(working, { type: 'MOVE_MISSED', combatantId: attackerId, moveId: move.id })
    return
  }

  const hitRoll = effect === 'damage.multiHit'
    ? rollHitCount(move.meta.minHits ?? 2, move.meta.maxHits ?? 5, working.state.rng)
    : { hits: 1, rng: working.state.rng }
  working.state = { ...working.state, rng: hitRoll.rng }

  const attackerTypes = typesOfActiveForm(working, attacker)
  const defenderTypes = typesOfActiveForm(working, target)
  const effectiveness = working.catalog.effectiveness(move.type, defenderTypes)
  let total = 0

  for (let hit = 1; hit <= hitRoll.hits; hit++) {
    const current = requireCombatant(working, attackerId)
    const victim = requireCombatant(working, targetId)
    if (!current || !victim || isCombatantFainted(victim)) break

    const result = computeDamage(
      {
        attacker: current,
        defender: victim,
        power: move.power ?? 0,
        category: move.category === 'special' ? 'special' : 'physical',
        moveType: move.type,
        attackerTypes,
        defenderTypes,
        critStage: move.meta.critRate ?? 0,
        // Gen VI Struggle ignores typing completely: no STAB, no chart, and it
        // hits a Ghost type as readily as anything else.
        appliesTyping: !asStruggle,
        effectiveness,
      },
      working.state.config,
      working.state.rng,
    )
    working.state = { ...working.state, rng: result.rng }
    total += applyDamage(working, targetId, result.damage, 'move', {
      sourceId: attackerId,
      critical: result.critical,
      effectiveness: result.effectiveness,
      hit,
    })
  }

  applyDrainOrRecoil(working, attackerId, move, effect, total, asStruggle)
  if (effect === 'damage.ailment') rollSecondaryAilment(working, attackerId, targetId, move)
  if (effect === 'damage.statChange') rollSecondaryStatChange(working, attackerId, targetId, move)
}

/**
 * The stat change of a damaging move: one roll, after the damage.
 *
 * A `chance` of 100 is not a roll that always wins — it is Overheat and Close
 * Combat, whose drop is part of the move. The draw is spent either way, so
 * adding one later cannot shift the rolls after it.
 */
function rollSecondaryStatChange(
  working: Working, attackerId: string, targetId: string, move: CatalogMove,
): void {
  const spec = move.meta.statChanges
  if (!spec) return
  const roll = drawChance(working.state.rng, spec.chance / 100)
  working.state = { ...working.state, rng: roll.rng }
  if (!roll.value) return

  // A target that fainted to the hit takes nothing more; a user's own drop
  // still lands, because it is the cost of the move it just used.
  const target = requireCombatant(working, targetId)
  if (spec.recipient === 'target' && (!target || isCombatantFainted(target))) return
  applyStatChanges(working, attackerId, targetId, move)
}

/**
 * Drain and recoil, both after the damage and both able to end a battle: a
 * recoil that faints the attacker is a real outcome, not an edge case.
 *
 * Struggle's recoil is the exception the games make too — a quarter of the
 * user's **max** HP, whatever the damage was.
 */
function applyDrainOrRecoil(
  working: Working,
  attackerId: string,
  move: CatalogMove,
  effect: SupportedEffect,
  damageDealt: number,
  asStruggle: boolean,
): void {
  if (asStruggle) {
    const attacker = requireCombatant(working, attackerId)
    if (!attacker) return
    const cost = Math.max(1, Math.floor(attacker.stats.hp * working.state.config.struggle.recoilFractionOfMaxHp))
    applyDamage(working, attackerId, cost, 'recoil', { sourceId: attackerId })
    return
  }
  if (damageDealt <= 0) return
  const drain = move.meta.drain ?? 0
  if (effect === 'damage.drain' && drain > 0) {
    applyHeal(working, attackerId, Math.max(1, Math.floor((damageDealt * drain) / 100)), 'drain')
  } else if (effect === 'damage.recoil' && drain < 0) {
    applyDamage(working, attackerId, Math.max(1, Math.floor((damageDealt * -drain) / 100)), 'recoil', {
      sourceId: attackerId,
    })
  }
}

/** The secondary effect of a move like Flamethrower: one roll, after the damage. */
function rollSecondaryAilment(
  working: Working, attackerId: string, targetId: string, move: CatalogMove,
): void {
  const chance = (move.meta.ailmentChance ?? 100) / 100
  const roll = drawChance(working.state.rng, chance)
  working.state = { ...working.state, rng: roll.rng }
  if (!roll.value) return

  const target = requireCombatant(working, targetId)
  if (!target || isCombatantFainted(target)) return
  const ailment = move.meta.ailment ?? 'none'
  if (ailment === 'confusion') applyConfusion(working, targetId)
  else if (isMajorStatusAilment(ailment)) applyMajorStatus(working, targetId, ailment, attackerId)
}
