// R31 — Regenerates the species base-stat catalog used by the profession
// affinity formula from the legacy archive (tag v0-legacy-baseline,
// data/pokemon-data.js → STATS_DB). The live `pokemon` table has no stat
// columns, so this is the only verified per-species stat source in the repo.
//
// Usage: node scripts/extract_legacy_base_stats.mjs
// Output: src/features/professions/domain/catalog/speciesBaseStats.ts

import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'

const TAG = 'v0-legacy-baseline'
const OUT = 'src/features/professions/domain/catalog/speciesBaseStats.ts'

const source = execFileSync('git', ['show', `${TAG}:data/pokemon-data.js`], { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 })
const match = source.match(/const STATS_DB=(\{[\s\S]*?\});/)
if (!match) throw new Error('STATS_DB not found in legacy pokemon-data.js')

const db = JSON.parse(match[1])
const ids = Object.keys(db).map(Number).sort((a, b) => a - b)
const rows = ids.map(id => {
  const stats = db[id]
  if (!Array.isArray(stats) || stats.length !== 6 || !stats.every(Number.isInteger)) {
    throw new Error(`Invalid stats for species ${id}`)
  }
  return `  ${id}: [${stats.join(', ')}],`
})

writeFileSync(OUT, `// GENERATED by scripts/extract_legacy_base_stats.mjs — do not edit by hand.
// Source: git tag ${TAG}, data/pokemon-data.js (STATS_DB), ${ids.length} species.
// Order: [hp, attack, defense, specialAttack, specialDefense, speed].
// Candidate for a future \`pokemon\` stat column; see docs/economy/POKEMON_PROFESSION_SYSTEM.md.

import type { BaseStatTuple } from '../types'

export const SPECIES_BASE_STATS: Readonly<Record<number, BaseStatTuple>> = {
${rows.join('\n')}
}
`)
console.log(`Wrote ${ids.length} species to ${OUT}`)
